package com.lucasferraz.cruddoctors.enums;

public enum MedicalSpecialty {
	ALERGOLOGIA,
	ANGIOLOGIA,
	BUCOMAXILO,
	CARIDIOLOGIACLINICA,
	CARDIOLOGIAINFANTIL,
	CIRURGIACABEÇAEPESCOCO,
	CURURGIACARDIACA,
	CIRURGIADETORAX;

}
